### PR TITLE
Sql is where you unique :) 

### PR DESCRIPTION
**Pull request by morrowc**
Moved a bunch of the hard logic into sql.

### CODE REVIEW

**Comment by gidoBOSSftw5731** [comment]
New SQL command:
```sql
SELECT inserttime, sum(deaths) as deaths, sum(confirmed) as confirmed, sum(tests) as tests, sum(recovered) as recovered FROM
        (SELECT date_trunc('hour', inserttime) as inserttime, sum(deaths) as deaths,
                sum(confirmed) as confirmed, sum(tests) as tests,
                sum(recovered) as recovered,
                count(combined) FROM records
        WHERE country = 'US'
        AND state = 'Virginia'
        GROUP BY inserttime
        ORDER BY inserttime desc) records
        GROUP BY inserttime
        ORDER BY inserttime desc;

```

**Comment by morrowc** [comment]
Ok, replacement query inserted. go! :)

**Comment by gidoBOSSftw5731** [comment]
Error while testing a graph:
```
gido-desk-deb-v2 discord_bot_go$ go run discord_bot_go.go
2020/04/10 00:34:11 [debug]     Covid19Bot has started on 5 servers
2020/04/10 00:34:15 [trace]     QueryURL: http://127.0.0.1/stateinfo/US/New York
2020/04/10 00:34:15 [trace]
2020/04/10 00:34:15 [error]     infinite x-range delta
```

**Comment by morrowc** [comment]
changes made. I need to see the output of logging on the bot now.

**Comment by gidoBOSSftw5731** [comment]
Same error as before on the graphing side of the bot: ```
gido-desk-deb-v2 discord_bot_go$ go run discord_bot_go.go
2020/04/10 01:29:32 [debug]     Covid19Bot has started on 5 servers
2020/04/10 01:29:35 [trace]     QueryURL: http://127.0.0.1/stateinfo/US/New York
2020/04/10 01:29:35 [trace]
2020/04/10 01:29:35 [error]     infinite x-range delta
``` 


API says it returned 0 entries, which sounds like the SQL clause it to blame, even though it (seems to)  iterate through it a few times

**Comment by morrowc** [comment]
> Same error as before on the graphing side of the bot: ```
> gido-desk-deb-v2 discord_bot_go$ go run discord_bot_go.go
> 2020/04/10 01:29:32 [debug] Covid19Bot has started on 5 servers
> 2020/04/10 01:29:35 [trace] QueryURL: http://127.0.0.1/stateinfo/US/New York
> 2020/04/10 01:29:35 [trace]
> 2020/04/10 01:29:35 [error] infinite x-range delta
> 
> ```

oh. I was hoping for some more logs with more useful data ;(

> 
> 
> API says it returned 0 entries, which sounds like the SQL clause it to blame, even though it (seems to)  iterate through it a few times
> ```

ah-ha, now working better.

**Comment by gidoBOSSftw5731** [comment]
Our SQL command doesnt work as intended
```sql
covid19scraper=# SELECT DISTINCT(date_trunc('hour', inserttime)) as inserttime, sum(deaths) as deaths,
        sum(confirmed) as confirmed, sum(tests) as tests,
        sum(recovered) as recovered,
        count(combined) FROM records
        WHERE country = 'US'
        AND state = 'Virginia'
        GROUP BY inserttime
        ORDER BY inserttime desc;
       inserttime       | deaths | confirmed | tests | recovered | count 
------------------------+--------+-----------+-------+-----------+-------
 2020-04-08 03:00:00-04 |     66 |      3335 |     0 |         0 |   134
 2020-04-05 23:00:00-04 |     52 |      2640 |     0 |         0 |   133
 2020-04-03 04:00:00-04 |     41 |      1706 |     0 |         0 |   102
 2020-03-30 03:00:00-04 |     20 |       890 |     0 |         0 |   134
 2020-03-26 04:00:00-04 |      9 |       397 |     0 |         0 |   133
 2020-03-25 03:00:00-04 |      9 |       304 |     0 |         0 |   133
(6 rows)

covid19scraper=# SELECT inserttime, sum(deaths) as deaths, sum(confirmed) as confirmed, sum(tests) as tests, sum(recovered) as recovered FROM
covid19scraper-#         (SELECT date_trunc('hour', inserttime) as inserttime, sum(deaths) as deaths,
covid19scraper(#                 sum(confirmed) as confirmed, sum(tests) as tests,
covid19scraper(#                 sum(recovered) as recovered,
covid19scraper(#                 count(combined) FROM records
covid19scraper(#         WHERE country = 'US'
covid19scraper(#         AND state = 'Virginia'
covid19scraper(#         GROUP BY inserttime
covid19scraper(#         ORDER BY inserttime desc) records
covid19scraper-#         GROUP BY inserttime
covid19scraper-#         ORDER BY inserttime desc;
       inserttime       | deaths | confirmed | tests | recovered 
------------------------+--------+-----------+-------+-----------
 2020-04-08 03:00:00-04 |    132 |      6670 |     0 |         0
 2020-04-05 23:00:00-04 |     52 |      2640 |     0 |         0
 2020-04-03 04:00:00-04 |     41 |      1706 |     0 |         0
 2020-03-30 03:00:00-04 |     40 |      1780 |     0 |         0
 2020-03-26 04:00:00-04 |      9 |       397 |     0 |         0
 2020-03-25 03:00:00-04 |      9 |       304 |     0 |         0
(6 rows)
```

**Comment by gidoBOSSftw5731** [comment]
New SQL:
```sql
SELECT date_trunc('hour', inserttime) as inserttime, sum(deaths) as deaths, sum(confirmed) as confirmed,
        sum(tests) as tests, sum(recovered) as recovered FROM
        (SELECT inserttime, sum(deaths) as deaths,
                sum(confirmed) as confirmed, sum(tests) as tests,
                sum(recovered) as recovered,
                count(combined) FROM records
        WHERE country = 'US'
        AND state = 'Virginia'
        AND inserttime > inserttime - interval '10 sec'
        AND inserttime < inserttime + interval '10 sec'
        GROUP BY inserttime
        ORDER BY inserttime desc) records
        GROUP BY inserttime
        ORDER BY inserttime desc;
```

**Pull request merged**
